package com.rainng.androidctl.agent.errors

enum class RpcErrorCode {
    INVALID_REQUEST,
    UNAUTHORIZED,
    RUNTIME_NOT_READY,
    ACCESSIBILITY_DISABLED,
    SNAPSHOT_UNAVAILABLE,
    NO_ACTIVE_WINDOW,
    STALE_TARGET,
    TARGET_NOT_FOUND,
    TARGET_NOT_ACTIONABLE,
    ACTION_FAILED,
    ACTION_TIMEOUT,
    SCREENSHOT_UNAVAILABLE,
    INTERNAL_ERROR,
}
