package com.rainng.androidctl.agent

object RequestBudgets {
    const val MAX_RPC_REQUEST_BODY_BYTES = 1 * 1024 * 1024

    const val ACTION_TIMEOUT_GRACE_MS = 1000L
    const val MAX_ACTION_TIMEOUT_MS = 15_000L

    const val DEFAULT_EVENTS_WAIT_MS = 0L
    const val DEFAULT_EVENTS_LIMIT = 20
    const val EVENTS_POLL_GRACE_MS = 1000L
    const val MAX_EVENTS_WAIT_MS = 30_000L

    const val META_METHOD_TIMEOUT_MS = 1000L
    const val DEVICE_METHOD_TIMEOUT_MS = 2000L
    const val APPS_LIST_METHOD_TIMEOUT_MS = 5000L
    const val SNAPSHOT_GET_METHOD_TIMEOUT_MS = 8000L

    const val OBSERVATION_TIMEOUT_DIVISOR = 4L
    const val MIN_TRANSITION_OBSERVATION_TIMEOUT_MS = 200L
    const val MAX_TRANSITION_OBSERVATION_TIMEOUT_MS = 1200L

    const val TYPE_VERIFICATION_TIMEOUT_DIVISOR = 4L
    const val MIN_TYPE_VERIFICATION_TIMEOUT_MS = 200L
    const val MAX_TYPE_VERIFICATION_TIMEOUT_MS = 1200L

    const val MAX_SCREENSHOT_SCALE = 2.0
    const val MAX_SCREENSHOT_BITMAP_BYTES = 64L * 1024L * 1024L
    const val MAX_SCREENSHOT_ENCODED_BYTES = 32L * 1024L * 1024L
    const val MAX_SCREENSHOT_BASE64_CHARS = ((MAX_SCREENSHOT_ENCODED_BYTES + 2L) / 3L) * 4L
    const val SCREENSHOT_CAPTURE_TIMEOUT_MS = 5000L
    const val SCREENSHOT_PROCESS_TIMEOUT_MS = 5000L
    const val SCREENSHOT_TIMEOUT_GRACE_MS = 1000L
    const val SCREENSHOT_METHOD_TIMEOUT_MS =
        SCREENSHOT_CAPTURE_TIMEOUT_MS +
            SCREENSHOT_PROCESS_TIMEOUT_MS +
            SCREENSHOT_TIMEOUT_GRACE_MS
    const val SCREENSHOT_PROCESSOR_MAX_THREADS = 1
    const val SCREENSHOT_PROCESSOR_KEEP_ALIVE_SECONDS = 30L
    const val SCREENSHOT_PROCESSOR_QUEUE_CAPACITY = 2

    const val METHOD_EXECUTOR_CORE_POOL_SIZE = 2
    const val METHOD_EXECUTOR_MAX_POOL_SIZE = 4
    const val METHOD_EXECUTOR_KEEP_ALIVE_SECONDS = 30L
    const val METHOD_EXECUTOR_QUEUE_CAPACITY = 16
}
