"""Stable daemon error contract models."""

from __future__ import annotations

from enum import Enum

from pydantic import Field

from .base import DaemonWireModel


class DaemonErrorCode(str, Enum):
    """Stable daemon error codes that cross the CLI and daemon boundary."""

    DAEMON_BAD_REQUEST = "DAEMON_BAD_REQUEST"
    DAEMON_UNAUTHORIZED = "DAEMON_UNAUTHORIZED"
    WORKSPACE_BUSY = "WORKSPACE_BUSY"
    RUNTIME_BUSY = "RUNTIME_BUSY"
    RUNTIME_NOT_CONNECTED = "RUNTIME_NOT_CONNECTED"
    SCREEN_NOT_READY = "SCREEN_NOT_READY"
    COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND"
    COMMAND_CANCELLED = "COMMAND_CANCELLED"
    REF_RESOLUTION_FAILED = "REF_RESOLUTION_FAILED"
    DEVICE_RPC_FAILED = "DEVICE_RPC_FAILED"
    DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"
    DEVICE_AGENT_UNAVAILABLE = "DEVICE_AGENT_UNAVAILABLE"
    DEVICE_AGENT_UNAUTHORIZED = "DEVICE_AGENT_UNAUTHORIZED"
    DEVICE_AGENT_VERSION_MISMATCH = "DEVICE_AGENT_VERSION_MISMATCH"
    DEVICE_AGENT_CAPABILITY_MISMATCH = "DEVICE_AGENT_CAPABILITY_MISMATCH"
    ACCESSIBILITY_NOT_READY = "ACCESSIBILITY_NOT_READY"
    DEVICE_RPC_TRANSPORT_RESET = "DEVICE_RPC_TRANSPORT_RESET"
    INTERNAL_COMMAND_FAILURE = "INTERNAL_COMMAND_FAILURE"
    WORKSPACE_UNAVAILABLE = "WORKSPACE_UNAVAILABLE"
    ARTIFACT_ROOT_UNWRITABLE = "ARTIFACT_ROOT_UNWRITABLE"
    ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"


class DaemonError(DaemonWireModel):
    """Typed daemon error payload for shared transport envelopes."""

    code: DaemonErrorCode
    message: str
    retryable: bool
    details: dict[str, object] = Field(default_factory=dict)
